version: "3.5"
services:
    tor:
        image: "arulrajnet/torprivoxy:latest"
        container_name: tor-dev
        
        ports:
            - 8118:8118 
            - 9050:9050 
            - 9051:9051
        restart: always  
       
    spider-dev:
        image: "hudsonwilde/spider-dev"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 3200:3202
            - 9229:9229
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: spider-dev
        volumes:
            - ".:/home/app"
        working_dir: /home/app
        environment:
            - DB_USER
            - DB_PASSWORD
            - CDNKEY=5c2c11b864e624852159 
            
        env_file:
            - /home/nick/q3server/spider/lake-server-dev.env
        restart: unless-stopped
    api-dev:
        image: "hudsonwilde/api-dev"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 3000:3000
            - 9030:9229
        build:
            context: .
            dockerfile: dev.Dockerfile
        container_name: api-dev
        volumes:
            - ".:/home/app"
        working_dir: /home/app
        environment:
            - DB_USER
            - DB_PASSWORD
            - CDNKEY=5c2c11b864e624852159 
            
        env_file:
            - /home/nick/q3server/q3api/q3api-dev.env
        restart: unless-stopped