version: "3.2"
services:
    tor:
        image: "arulrajnet/torprivoxy:latest"
        container_name: tor
        ports:
            - 8118:8118 
            - 9050:9050 
            - 9051:9051
        restart: always    
    #db:
    #    image: mariadb
    #    restart: always
    #    environment:
    #        - MARIADB_USER
    #        - MARIADB_PASSWORD
    #        - MARIADB_ROOT_PASSWORD
    #        - MYSQL_TCP_PORT
    #        - MYSQL_UNIX_PORT
    #
    #
    #    ports:
    #        - 3306:3306
    #adminer:
    #    image: adminer
    #    restart: always
    #    ports:
    #    - 8080:8080

    redis:
        image: "redislabs/redisearch"
        container_name: redis
        ports:
            - 3679:3679
        restart: unless-stopped     
    spider:
        image: "hudsonwilde/spider:latest"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 3212:3202
            - 9239:9229
        build:
            context: .
            dockerfile: Dockerfile
        container_name: spider
        volumes:
            - "homeapp:/home/app"
        working_dir: /home/app
        environment:
            - DB_USER
            - DB_PASSWORD
            - CDNKEY
            
        env_file:
            - /home/nick/spider2/spider.env
        restart: unless-stopped
    delete-spam:
        image: "hudsonwilde/delete-spam:latest"
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        ports:
            - 3213:3202
            - 9238:9229
        build:
            context: .
            dockerfile: spam.Dockerfile
        container_name: delete-spam
        volumes:
            - "homeapp2:/home/app"
        working_dir: /home/app
        environment:
            - DB_USER
            - DB_PASSWORD
            - CDNKEY
            
        env_file:
            - /home/nick/spider2/spider.env
        restart: unless-stopped  
    
   
volumes:
    homeapp:
        driver: local  
    homeapp2:
        driver: local  
       
